Remove ELFs from access.rb and tmpl files.
pulibrary/bibdata pull request #1215
Opened 2021-04-07 22:05 UTC by tpendragon

I need to get the fixture out of the full dump that I need, but my alma user doesn't have permission to run publishing profiles. I'm blocked until I get the MARC record for 99121576653506421.

Work towards #1203

2021-04-08 15:18 UTC, christinach approved these changes
This is ok but when we run to generate the tables form alma the elf will be again in the tmpl files.

2021-04-08 15:22 UTC, tpendragon commented
> This is ok but when we run to generate the tables form alma the elf will be again in the tmpl files.

Yes, but the test will fail.

2021-04-08 15:22 UTC, christinach commented
the elfs need to be removed from alma or  to exclude them in this method https://github.com/pulibrary/bibdata/blob/a973974e41920cbf4507d5f854e400519defd5b5/app/services/location_data_service.rb#L23 when we populate the tables. 
Your pr will work as long as we dont update the tables from alma which I will do when I update the flags for my pr. 
I'm ok if you want to go ahead and merge this and I will exclude the elfs in https://github.com/pulibrary/bibdata/pull/1213

2021-04-08 15:23 UTC, eliotjordan requested changes
Small change requested, otherwise 👍

2021-04-08 15:23 UTC, eliotjordan commented on spec/marc_to_solr/lib/config_spec.rb
> +      # I need a record where this would break without this change - probably 99121576653506421
Don't need this comment anymore.

2021-04-08 15:24 UTC, christinach commented
> > This is ok but when we run to generate the tables form alma the elf will be again in the tmpl files.
> 
> Yes, but the test will fail.

Yes you are right the test will fail.

2021-04-08 15:32 UTC, tpendragon commented
To be clear, after deploying this we'll have to delete the DB entries for the elf locations from bibdata-alma.

2021-04-09 16:07 UTC, christinach commented
I'm sorry @tpendragon this needs a rebase

2021-04-12 13:37 UTC, christinach commented
It's ok to merge and have the test in place.

2021-04-12 13:37 UTC, christinach approved these changes

2021-04-12 13:40 UTC, merged