Availability endpoint and temp locations
pulibrary/bibdata pull request #1299
Opened 2021-05-04 15:23 UTC by hectorcorrea

@hackartisan @eliotjordan This PR makes some changes to the Availability endpoint to better handle the different kind of `inventory_types` (physical, electronic, digital) that Alma returns. 

Notice that I changed a few keys/values of the attributes returned in the API (i.e. it will break Orangelight) but I think these keys/values make more sense now that we understand what Alma does.

I am also adding a boolean `temp_location` that we can use in Orangelight to add something in the web page to request more Availability information for these records (see [notes on 4/29](https://docs.google.com/document/d/1sq_DmkRVLWEQdwf0YY1Dl3KGYlPd_0ldCYYc6PTcOuY/edit) about this)

Addresses #1190

2021-05-06 20:52 UTC, hectorcorrea commented on spec/adapters/alma_adapter_spec.rb
> +    it "reports availability (without holding_id) for items in temporary locations" do
This test and the one below it are the only relevant test for handling temporary locations. The rest of the changes in the tests are to account for the slightly different response that we returning now that we are only reporting on physical items (i.e. ignoring electronic portfolios and digital items)

2021-05-06 20:53 UTC, hectorcorrea commented on app/adapters/alma_adapter.rb
> +    if temp_locations && deep_check
This is the new behavior that the client can request via the deep_check parameter to drill down for more information if the initial call reports holdings in temporary locations.

2021-05-06 20:55 UTC, hectorcorrea commented on app/adapters/alma_adapter/availability_status.rb
> +    def bib_availability_from_items
This method is brand new: `item_data` makes a call to the Alma API to fetch item-level information that we use when the client asks for a "deep_check".

2021-05-06 20:55 UTC, hectorcorrea commented on app/adapters/alma_adapter/availability_status.rb
> +    def holding_status(holding:, sequence:)
This method is now greatly simplified because we are ONLY handling physical inventory and ignoring electronic and digital.

2021-05-06 20:59 UTC, hectorcorrea commented on app/adapters/alma_adapter/availability_status.rb
> +    def holding_status_from_item(alma_item)
This method is new. 

This method builds a response that is identical to what the method `holding_status` (just above this one) returns.

This new method builds the response from the data coming from Alma's `/bib/{id}/holdings/all/items` API as opposed to the information in the AVA fields in the Alma's `/bib/{id}` endpoint.

2021-05-07 15:11 UTC, hackartisan requested changes
Just one small request

2021-05-07 17:07 UTC, hectorcorrea commented on app/adapters/alma_adapter/availability_status.rb
> +    def holding_status_from_item(alma_item)
Good idea. Done.

2021-05-07 19:13 UTC, hackartisan approved these changes

2021-05-07 19:14 UTC, merged