Process SCSB Boundwith Records
pulibrary/bibdata pull request #1303
Opened 2021-05-06 20:24 UTC by eliotjordan

- Adds CachedMarcRecord model
- Extracts boundwith records from SCSB dumpfiles
- Processes and saves records in a new scsb dumpfile

Progress towards #1255

2021-05-07 15:40 UTC, hackartisan commented on app/jobs/recap_dump_file_processing_job.rb
> +          if boundwiths && scsb_record.boundwith?
yesss that looks so much nicer

2021-05-07 16:51 UTC, hectorcorrea commented on app/adapters/alma_adapter/scsb_dump_record.rb
> +    # 852/866/867/868 fields which have a subfield "8" are all copied from
Perhaps indicate that the subfield "8" represents the holding_id ?

2021-05-07 17:28 UTC, christinach requested changes
It looks great. Some comments updates.

2021-05-07 17:28 UTC, christinach commented on app/jobs/recap_boundwiths_processing_job.rb
> +    # to set of boundwith records.
I'm sorry a small spelling mistake. constiuent

2021-05-07 17:28 UTC, christinach commented on app/jobs/recap_boundwiths_processing_job.rb
> +          # Get host record id from a constituent[773] and
can we specify 773w ?

2021-05-07 17:28 UTC, christinach commented on app/jobs/recap_boundwiths_processing_job.rb
> +        # Fetch constituent record ids from host[774] and retrieve from Alma or
can we specify in the comment 774w?

2021-05-10 13:06 UTC, hackartisan requested changes
I wanted to record a couple of blocking concerns that have come out of slack discussion:

1. This process as written is not idempotent. That is, if the code errors in the process of creating / saving the boundwith file, the records will no longer be in the other files in order to rerun it. Such an error seems likely to happen at some point, given that we're doing network stuff and working with marc records.
2. There is a race condition in the way it's written. With each dump file being stripped of its boundwith records at the same time as they are scanned for boundwith records, we will undoubtedly loose some.

We need to make adjustments to address these concerns.

2021-05-11 13:44 UTC, hackartisan requested changes
Also we should add a test for the case where there were no boundwiths in the dump

2021-05-11 13:44 UTC, hackartisan requested changes
Also we should add a test for the case where there were no boundwiths in the dump

2021-05-12 13:08 UTC, hackartisan approved these changes
They're all temp files now. Should get around both the race condition and make it idempotent. I can't think of a use case that requires us to store them, as long as they get to the s3 drive. Seems great! 🎉

2021-05-12 13:27 UTC, christinach approved these changes

2021-05-12 13:27 UTC, merged