Adding modified Alma fixtures in order to ensure that the test suites for advanced_location_s and location_code_s/location_display are now passing
pulibrary/bibdata pull request #1419
Opened 2021-06-15 17:44 UTC by jrgriffiniii

Resolves #1247

2021-06-15 17:46 UTC, christinach requested changes
@jrgriffiniii in Alma we don't have elf locations. We should not test with modified elf fixtures.

2021-06-15 17:56 UTC, christinach commented
In other words we should remove elf tests. Because of the initial migration elf location still exists in alma but it is a cleanup issue and it will be removed. Also when we generate the locations tables we exclude the elf locations.

2021-06-15 18:22 UTC, christinach commented
We are testing online locations using the electronic_portfolio_s field, so we can close this pr. I'm sorry that the issue was not updated after we added the electronic_portfolio_s field.

2021-06-15 18:43 UTC, christinach commented
for reference I'm adding my comment from the issue https://github.com/pulibrary/bibdata/issues/1247#issuecomment-861744423. it references an example and the test for the electronic portfolio_s field.

2021-06-16 13:06 UTC, jrgriffiniii commented
I am very sorry for misunderstanding the scope of this issue, I will proceed with simply deleting the tests.

2021-06-17 13:19 UTC, christinach requested changes

2021-06-17 13:19 UTC, christinach commented on spec/fixtures/marc_to_solr/9992320213506421_elf1.mrx
> +  <controlfield tag="005">20201006134116.0</controlfield>
@jrgriffiniii can you please remove this fixture?

2021-06-17 13:19 UTC, christinach commented on spec/fixtures/marc_to_solr/9992320213506421_elf2.mrx
> +  <controlfield tag="005">20201006134116.0</controlfield>
can you please remove this fixture as well?

2021-06-17 13:19 UTC, christinach commented on spec/marc_to_solr/lib/config_spec.rb
>      end
can we make this let one line?

2021-06-17 13:19 UTC, christinach commented on spec/marc_to_solr/lib/config_spec.rb
> +
can we also change these lets to one line?

2021-06-17 13:19 UTC, christinach commented on spec/marc_to_solr/lib/config_spec.rb
> +  end
can we change these lets to one line?

2021-06-17 13:19 UTC, christinach commented on spec/marc_to_solr/lib/config_spec.rb
>      end
can we change the let to one line?

2021-06-17 20:29 UTC, christinach approved these changes

2021-06-17 20:31 UTC, merged