Adds rake task to register a local PARTNER_RECAP file into the database
pulibrary/bibdata pull request #1425
Opened 2021-06-16 15:14 UTC by hectorcorrea

Fixes #1422

2021-06-16 15:22 UTC, christinach requested changes
@hectorcorrea thank you. I was thinking about this rake task to be more flexible across the different dump types and dump file types. I added a couple of questions. Also a mapping between DUMP_TYPE and DUMP_FILE_TYPE as a comment in the beginning of the rake task would be good.

2021-06-16 15:22 UTC, christinach commented on lib/tasks/scsb.rake
> +    dump = Dump.new(event_id: ev.id, dump_type_id: dump_type_id)
can we add constant: DUMP_TYPE so that we can pass any constant we want when we run the rake task?

2021-06-16 15:32 UTC, hectorcorrea commented
@christinach Made the changes that you requested. Notice that I left it with the defaults for RECAP files if no DUMP_TYPE and DUMP_FILE_TYPE are indicated.

2021-06-16 15:33 UTC, hectorcorrea commented
@christinach I am not sure I follow this: "Also a mapping between DUMP_TYPE and DUMP_FILE_TYPE as a comment in the beginning of the rake task would be good."

2021-06-22 13:50 UTC, hackartisan commented on lib/tasks/scsb.rake
> +    ev = Event.new(success: true)
I think the events page will fail to load in the UI unless it has some start / end dates. I almost never use the UI in development, though; doesn't seem worth blocking over.

2021-06-22 13:50 UTC, hackartisan approved these changes

2021-06-22 13:50 UTC, merged