Refactors the RSpec test suites and introduces Alma test fixtures
pulibrary/bibdata pull request #1443
Opened 2021-06-24 17:54 UTC by jrgriffiniii

Advances #1204 and deprecates https://github.com/pulibrary/bibdata/pull/1430

2021-06-24 20:17 UTC, hackartisan requested changes
The tests read better now and are more descriptive and explicit, thank you.

I left one change request inline.

Otherwise, I don't think I totally understand the newly-pending tests. They seem to have fixtures in this PR -- is it just a matter of reenabling them or is there more to it?

2021-06-24 20:17 UTC, hackartisan commented on spec/marc_to_solr/lib/config_spec.rb
> +    xit "returns the electronic_portfolio_s field" do
Sort of confused -- it looks like the fixture is in this PR -- is the test broken?

2021-06-24 20:17 UTC, hackartisan commented on spec/marc_to_solr/lib/config_spec.rb
> +    context '' do
Do we know what should go here?

2021-06-24 20:17 UTC, hackartisan commented on spec/marc_to_solr/lib/config_spec.rb
> +      # This test needs to be restored (please see https://github.com/pulibrary/bibdata/issues/1204)
Don't worry about this one -- the Hathi functionality won't be used anymore once we launch Alma

2021-06-29 13:48 UTC, christinach requested changes
@jrgriffiniii all the numismatics fixtures should have location_code: `rare$num`. This is the new location for numismatics. I would customize the specific fixtures and update the value of the location_code.

2021-07-02 15:26 UTC, jrgriffiniii commented
I have shifted work to a differed (rebased) branch (https://github.com/pulibrary/bibdata/compare/alma...issues-1204-jrgriffiniii-replace-fixtures-fixed), and I am waiting to ensure that the test suites are passing: https://app.circleci.com/pipelines/github/pulibrary/bibdata?branch=issues-1204-jrgriffiniii-replace-fixtures-fixed

2021-07-02 16:38 UTC, jrgriffiniii commented
I am sorry, I am deprecating this again in favor of https://github.com/pulibrary/bibdata/pull/1474

2021-07-02 16:38 UTC, closed without merging