Updated refactoring for the RSpec test suites and the introduction of Alma test fixtures
pulibrary/bibdata pull request #1474
Opened 2021-07-02 16:37 UTC by jrgriffiniii

Advances #1204 and deprecates #1443

2021-07-02 18:14 UTC, christinach requested changes
@jrgriffiniii I can show you how to export fixtures from alma. My understanding is that you used the bibliographic endpoint which lead to all the unnecessary changes in princeton_marc and traject_config. The fixtures for the indexing should be exported from the alma back end.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/princeton_marc.rb
> +# assumes exactly 1 AVA is present per mfhd (it saves the last AVA it finds)
@jrgriffiniii I havent looked the whole Pr but when we index from the mrc files that we export from alma they include the enrichment fields 852. They dont include AVA. The AVA is a tag that comes back only through the Alma API call. Please reverse the changes in princeton_marc file.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
>  each_record do |record, context|
Same here. Please reverse the changes. The location_code is a compination of 852|b and 852|c

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
>        if s_field.code == 'b'
The comments should be 852 not AVA.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
> +    accumulator << field['d']
Same here. Please reverse the changes to 852.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
>    end
Please reverse to 852.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
Please reverse to 852.

2021-07-02 18:14 UTC, christinach commented on marc_to_solr/lib/traject_config.rb
>      fields << field
Same here. AVE is a tag that comes from the Alma api call. In the exported files the data enrichment has 951 field. Please reverse the change.

2021-07-02 18:14 UTC, christinach commented on spec/fixtures/marc_to_solr/991583506421.mrx
>      <subfield code="8">22262098640006421</subfield>
I'm assuming you created the mrx using the bibdata bibliographic endpoint. Please use the sets in alma to export the desired fixtures.

2021-07-02 18:14 UTC, christinach commented on spec/fixtures/marc_to_solr/alma/README.md
> +
The mms ids should be used to export the desired fixtures from alma back end.

2021-07-07 19:17 UTC, hackartisan commented
replaced by https://github.com/pulibrary/bibdata/pull/1491

2021-07-07 19:17 UTC, closed without merging