Finish migrating indexing docs from google doc
pulibrary/bibdata pull request #1519
Opened 2021-07-12 20:45 UTC by hackartisan

This gets everything migrated; we'll of course have to keep updating this documentation as things change.

Many parts of that google doc are no longer relevant since we're moving off of voyager.

Note that I didn't migrate the recommendation to use the catalog-staging instance for observing the indexing process. It could introduce inconsistencies with regard to the numismatics items via sneakers. Instructions for hooking up a local dev instance to the index were migrated for observing via the orangelight UI.

closes #897

2021-07-12 20:50 UTC, tpendragon approved these changes

2021-07-12 21:09 UTC, escowles commented on docs/indexing.md
>  About 68,800 senior theses pulled from the OIT Dataspace repository http://dataspace.princeton.edu/jspui/handle/88435/dsp019c67wm88m
Probably good to remove OIT here.

2021-07-12 21:12 UTC, escowles commented on docs/indexing.md
> +Because traject does not log to datadog we lose log output for indexing that runs in the background. See https://github.com/pulibrary/bibdata#1507
The link doesn't work for me, so I think it should be https://github.com/pulibrary/bibdata/issues/1507

2021-07-12 21:25 UTC, christinach commented on docs/call-numbers.md
> +
ssh to catalog-qa1 for staging or catalog.. for production.

2021-07-12 22:10 UTC, christinach requested changes

2021-07-12 22:10 UTC, christinach commented on docs/indexing.md
> +- `> solr.delete_by_query("id:SCSB*")`
This is ok to keep.

2021-07-12 22:10 UTC, christinach commented on docs/indexing.md
> +### Delete records from voyager, but leave scsb / thesis records
Can we update to `Delete records from Solr, excluding SCSB and Theses`

2021-07-12 22:10 UTC, christinach commented on docs/indexing.md
> +- `> solr_url = "http://lib-solr.princeton.edu:8983/solr/catalog-rebuild"`
`solr_url = "http://lib-solr8-prod.princeton.edu:8983/solr/catalog-rebuild"`

2021-07-12 22:10 UTC, christinach commented on docs/call-numbers.md
> +
navigate to /opt/orangelight/current

2021-07-12 22:40 UTC, christinach requested changes

2021-07-12 22:40 UTC, christinach commented on docs/call-numbers.md
> +
To fully regenerate all browse lists:
-  on catalog-staging `ssh to a staging box`, cd `/opt/orangelight/current` and run: ... (There are no workers for catalog-staging and the rake task needs to run on the catalog box.)
- for catalog production `ssh to catalog-indexer1` (confirm through the crontab that it's running the call numbers and not other rake tasks), cd `/opt/orangelight/current` and run: ...

2021-07-12 22:40 UTC, christinach commented on docs/call-numbers.md
> +ssh to `lib-pulindexer1`. Check the crontab and make sure the rake task for the call numbers runs on this box. If not then check `lib-pulindexer2` and `lib-pulindexer3`.
catalog-indexer1, catalog-indexer2, catalog-indexer3. Currently the call_numbers task is deployed to run on catalog-indexer1 check the crontab to confirm.

2021-07-13 14:29 UTC, hackartisan commented
Thank you for the careful review. I've made the recommended changes; ready for re-review

2021-07-13 14:38 UTC, christinach requested changes

2021-07-13 14:38 UTC, christinach commented on docs/call-numbers.md
> +ssh to `lib-pulindexer1`. Check the crontab and make sure the rake task for the call numbers runs on this box. If not then check `lib-pulindexer2` and `lib-pulindexer3`.
@hackartisan can you update the worker names? ^

2021-07-13 15:39 UTC, hackartisan commented
@christinach fixed, thank you.

2021-07-13 15:42 UTC, christinach approved these changes
Thank you @hackartisan

2021-07-13 16:02 UTC, merged