remove get_catalog_date_from_record method
pulibrary/bibdata pull request #1585
Opened 2021-08-06 21:30 UTC by zaymasood

2021-08-09 12:58 UTC, hackartisan requested changes
I think we can be more aggressive and delete all the code changes from https://github.com/pulibrary/bibdata/pull/1112/files.

Could you also please check whether there are other tests using the fixtures added in that PR? If there aren't we can delete the fixtures, as well.

2021-08-10 13:53 UTC, hackartisan approved these changes
This looks good to me -- the other small changes from #1112 don't appear to be in the code anymore.

@hectorcorrea maybe you could take a look before we merge?

2021-08-10 13:58 UTC, hectorcorrea approved these changes

2021-08-10 13:59 UTC, hectorcorrea commented
Well done @zaymasood !

2021-08-10 14:32 UTC, merged