Updating Thesis commands to include tmux and bundle exec
pulibrary/bibdata pull request #1808
Opened 2022-03-03 17:01 UTC by carolyncole

2022-03-03 19:49 UTC, sandbergja requested changes
Thanks so much for writing this up, @carolyncole !

2022-03-03 19:49 UTC, sandbergja commented on docs/indexing.md
> +curl 'http://lib-solr8-prod.princeton.edu:8983/solr/catalog-alma-production-rebuild/update?commit=true' --data-binary @/home/deploy/theses.json -H 'Content-type:application/json'
just needs a `$ ` at the start of this line as well.

2022-03-04 14:41 UTC, carolyncole commented
@sandbergja good catch!  Thank you!  It's been updated.

2022-03-04 15:48 UTC, sandbergja approved these changes

2022-03-04 15:48 UTC, merged