update the ansible name of the orangelight machines
pulibrary/bibdata pull request #1809
Opened 2022-03-03 17:15 UTC by carolyncole

2022-03-03 20:15 UTC, christinach requested changes

2022-03-03 20:15 UTC, christinach commented on docs/indexing.md
the name is `orangelight_production` https://github.com/pulibrary/princeton_ansible/blob/2949e896c6f2f8685434dcfe2444092bd00f9149/hosts#L110

2022-03-04 14:39 UTC, carolyncole commented
Thanks @christinach.  I updated it.

2022-03-04 14:40 UTC, christinach approved these changes

2022-03-04 14:40 UTC, christinach requested changes
`orangelight_production`

2022-03-04 14:41 UTC, christinach requested changes

2022-03-04 14:41 UTC, christinach commented on docs/indexing.md
orangelight_production ..

2022-03-07 16:00 UTC, sandbergja approved these changes

2022-03-07 16:02 UTC, merged