Add rake task to request full records from SCSB
pulibrary/bibdata pull request #1953
Opened 2022-08-18 14:06 UTC by maxkadel

@kevinreiss  - I'm I right in thinking that the response:

```
Received unexpected response: Can't run export now as another process is in progress. We have saved your request.We will initiate and notify once the exiting process completes
```

means that requests after the first one are in the queue and will be processed once the first one is done?

If I'm mistaken, we should change the rake task to only request from one institution at a time, which could be passed in from the environment as well.

Closes #1544

2022-08-18 14:51 UTC, kevinreiss commented
Yes, we would want to run the task one institution at a time. Yes, if make the calls for each partner close together you'll get the text response you posted. The application will start your job when the first partner dump requested concludes. Notifications will go to the email address passed in the API call.

2022-08-18 14:53 UTC, kevinreiss commented
I'm wondering if ultimately we'd want to create a scheduled task to generate a full dump from each partner say, every two weeks so we'll always have a relatively fresh copy available to us. @mzelesky and @pmgreen also both refer to this dataset for reporting and collection analysis reports so it might beneficial for them to have this data be available in a relatively current form.

2022-08-18 14:54 UTC, kevinreiss requested changes

2022-08-18 14:54 UTC, kevinreiss commented on app/models/scsb_full_records_request.rb
> +      req.params['imsDepositoryCodes'] = 'RECAP,HD'
I wonder if this should be a parameter. Harvard is the only partner that has items in both facilities, for CUL and NYPL you'd only ask for "RECAP".

2022-08-18 14:59 UTC, maxkadel commented
> I'm wondering if ultimately we'd want to create a scheduled task to generate a full dump from each partner say, every two weeks so we'll always have a relatively fresh copy available to us. @mzelesky and @pmgreen also both refer to this dataset for reporting and collection analysis reports so it might beneficial for them to have this data be available in a relatively current form.

In that case, would this code more appropriately live in lib_jobs?

2022-08-19 20:36 UTC, kevinreiss commented on config/schedule.rb
> +  rake "scsb:request_records[production,mk8066@princeton.edu,CUL]", output: "/tmp/cron_log.log"
Unfortunately the output from the API is pretty minimal, so having the email notifications is really the only way to get a record of what the job does. I'm thinking we should get a service account like Carolyn suggested to receive them so we don't have one our addresses hardcoded in the config.

2022-08-19 20:37 UTC, kevinreiss approved these changes

2022-08-19 20:50 UTC, merged