maint: removed deprecated endpoints
pulibrary/bibdata pull request #2225
Opened 2023-07-29 08:26 UTC by haiderashfaq

resolves #2192

2023-07-31 21:23 UTC, sandbergja approved these changes
Thanks, @haiderashfaq !

2023-08-01 17:28 UTC, sandbergja requested changes
@haiderashfaq -- now that the tests have run, it looks like there are several failing tests.  Could you please address those as part of your branch?  I believe most of them can just be deleted.

2023-08-01 18:24 UTC, haiderashfaq commented
> @haiderashfaq -- now that the tests have run, it looks like there are several failing tests. Could you please address those as part of your branch? I believe most of them can just be deleted.

all of the failed cases were for removed deprecated routes and actions.  So, removed test cases for them as well.

2023-08-02 12:56 UTC, sandbergja requested changes
Thanks, @haiderashfaq , it's looking good! Just two small requests.

2023-08-02 12:56 UTC, sandbergja commented on spec/routing/bibliographic_routing_spec.rb
> -    it "routes to #item_discharge" do
Since this file no longer has any tests, could you please delete it outright?

2023-08-02 13:15 UTC, merged